### ISSUE TITLE
gdk-pixbuf removed the pixdata loader

### ISSUE THREAD

**Issue by dffischer** [Abraca/Abraca#37]
With [commit 349fab9](https://github.com/GNOME/gdk-pixbuf/commit/349fab92825573d45b41184d5027436fcd969cc4), the pixdata loader was removed from [gdk-pixbuf](https://github.com/GNOME/gdk-pixbuf/) due to security reasons. Without it, Abraca is unable to start and only yields the following error.

```
** (abraca:22549): ERROR **: abraca-application.vala:123: unrecognized image file format
```

That means abraca is currently incompatible with gdk-pixbuf version 2.36.1 and all newer variants.

**Comment by dsvensson** [comment]
Thanks, I'll look into it.

**Comment by dffischer** [comment]
And the error is gone again since [commit c7b58ac](https://github.com/GNOME/gdk-pixbuf/commit/c7b58acd3b157512407bc85497cd9cd2da40ab3c). Technically, [commit 0af5d60](https://github.com/GNOME/gdk-pixbuf/commit/0af5d60d0247e49ac6cc76f8b0c2af36bd20d391) brought the fix, but only its successor will compile. Abraca starts fine with any gdk-pixbuf version containing them.

Since the same time, the desktop symbol for Abraca disappeared (it is an empty icon now), but that may be a coincidence.
